server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  file:
    path: D:\Work\capstone\log
  level:
    com:
      edu:
        capstone:
          mapper: DEBUG
    org:
      springframework:
        transaction:
          interceptor: TRACE
        security: DEBUG